# Generated by Django 2.2.7 on 2019-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('complete_date', models.DateField(auto_now_add=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
